import type { Metadata } from "next";

import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";

import "@aws-amplify/ui-react/styles.css";
import ConfigureAmplifyClientSide from "@/components/auth/configureAmplifyClientSide/ConfigureAmplifyClientSide";
import Header from "./components/header/Header";
import ReduxProvider from "./providers/reduxProvider";
import CheckAuth from "./components/auth/Auth";
import { Amplify } from "aws-amplify";
import outputs from "../amplify_outputs.json";
import { ReactQueryProvider } from "./providers/reactQueryProvider";
import { BreadCrumb } from "./components/breadCrumb/BreadCrumb";

Amplify.configure(outputs);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConfigureAmplifyClientSide />
        <Theme>
          <ReactQueryProvider>
            <ReduxProvider>
              <CheckAuth />
              <Header />

              <Container size="4" className="!m-0 !p-0">
                <BreadCrumb  />
                {children}
              </Container>
            </ReduxProvider>
          </ReactQueryProvider>
        </Theme>
      </body>
    </html>
  );
}
