import type { Metadata } from "next";

import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";

import "@aws-amplify/ui-react/styles.css";
<<<<<<< Updated upstream
import ConfigureAmplifyClientSide from "@/components/configureAmplifyClientSide/ConfigureAmplifyClientSide";
import Header from "./components/header/Header";
import ReduxProvider from "./stores/redux/provider";
import CheckAuth from "./components/auth/Auth";
=======
import ConfigureAmplifyClientSide from "@/app/components/configureAmplify/ConfigureAmplify";
import Header from "./components/header/Header";

const inter = Inter({ subsets: ["latin"] });
>>>>>>> Stashed changes

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConfigureAmplifyClientSide />
        <Theme>
<<<<<<< Updated upstream
          <ReduxProvider>
            <CheckAuth />
            <Header />
            <Container className="mt-16" size="4">
              {children}
            </Container>
          </ReduxProvider>
=======
          <Header />
          {children}
>>>>>>> Stashed changes
        </Theme>
      </body>
    </html>
  );
}
