name: deploy-dev

on:
  workflow_dispatch: # Allows the workflow to be triggered manually via a button in GitHub Actions

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
      run:
        - uses: actions/checkout@dev
        - name: Run curl command
          run: |
            echo "Running curl command..."
            curl -X POST -d {} "https://webhooks.amplify.eu-west-2.amazonaws.com/prod/webhooks?id=bef90eb2-cc95-4096-983f-7c3e0e9eb646&token=tnYS9AGc7TLdlitkA2gRGXeamlPNS1oae77xrRfBqWg&operation=startbuild" -H "Content-Type:application/json"
            echo "Curl command completed."
