name: deploy-dev

on:
  workflow_dispatch: # Allows the workflow to be triggered manually via a button in GitHub Actions

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
      - name: Run curl command
        run: |
          echo "Running curl command..."
          curl -X POST -d {} "https://webhooks.amplify.eu-west-2.amazonaws.com/prod/webhooks?id=${{secrets.AMPLIFY_DEV_DEPLOY_WEBHOOK_ID}}&operation=startbuild" -H "Content-Type:application/json"
          echo "Curl command completed."
