name: Promote Dev to Main

on:
  workflow_dispatch: # Allows the workflow to be triggered manually via a button in GitHub Actions


jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      # Step 3: Increment version in package.json
      - name: Increment version
        id: version
        run: |
          # Read the current version from package.json
          VERSION=$(jq -r '.version' package.json)
          echo "Current version: $VERSION"

          # Increment the patch version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"

          # Update the version in package.json
          jq ".version = \"$NEW_VERSION\"" package.json > tmp.json && mv tmp.json package.json

          # Output the new version for later steps
          echo "::set-output name=new_version::$NEW_VERSION"

      # Step 4: Commit version bump to dev
      - name: Commit version bump to dev
        run: |
          git add package.json
          git commit -m "Bump version to ${{ steps.version.outputs.new_version }}"
          git push origin dev

      # Step 5: Merge dev into main
      - name: Merge dev into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev --no-ff -m "Promote dev to main"
          git push origin main